/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import module.interf.IHello;

import java.util.ServiceLoader;

public class App {
    public String getGreeting() {
        return "ServiceLoader Test";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ServiceLoader<IHello> loader = ServiceLoader.load(IHello.class);
        for (IHello iHello : loader) {
            System.out.println(iHello.sayHello());
        }
    }
}
